feat: 소식 UI 개발
cnu-bot/cnubot-client-app pull request #12
Opened 2022-10-19 13:47 UTC by CheolheeLee0

# Describe your changes

- [x] #11 

### 영상으로 확인하기

[![Video Label](http://img.youtube.com/vi/y4_hiaOdu1o/0.jpg)](https://www.youtube.com/shorts/y4_hiaOdu1o)
<br>

- 소식 페이지 UI 개발
	- 상단 로고
	- 홈 버튼
	- enum 적용
		- 게시판 종류 선택 (BoardType)
		- 백마광장 종류 선택 (WhiteHorseSquareType)
		- 국제교류본부 종류 선택 (InternationalHqType)
	- 게시글 임시 모델 생성 (NoticeModel) - freezed
		- 더미 데이터 5개 생성
	- 게시글 클릭 시 웹링크 이동하도록 변경
	- Button, ListView, Logo 등 위젯 컴포넌트화
	- notice 화면에서만 쓰이는 것들은 4_view/3_notice/component에 저장
	- 다른 화면에도 쓰일 수 있는 것들은 4_view/1_component에 저장 
- kHeadLine1~5 (상단 텍스트) textstyle 등록
- kBody1~4 (게시글에 사용된 텍스트) textstyle 등록
- bottom navigation svg icon 등록

- 소식 API 기본 로직 정리
	- Binding, Controller, Repository, Provider 생성
	- dio - cache interceptor 추가
		- 로컬 MemCacheStore에 캐시 데이터 저장
			- Total allowed size in bytes (7MB by default).
			- Volatile cache with LRU strategy, LRU 알고리즘 사용
		- 새 데이터 갱신 기준
			- maxStale (이후 몇 시간으로 할 지 논의 필요)
			- refresh == true를 넣어주면, 갱신
			- refresh == false 이면 API 요청하지 않고 메모리에서 가져옴

Fixes #11 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Next Step Todo (optional)

- 소식 백엔드 API연동
- 서버 상황에 따라 API 캐싱 전략 수정

## Questions

- 💬 질문 사항이에요!
	- 코드 conflict가 우려되는 부분 있으면 말씀해주시면 수정하겠습니다!

2022-10-19 20:56 UTC, ChanhyukPark-Tech commented
@CheolheeLee0 좋은 기여 감사합니다!
![2336B3D1-60BA-4635-B218-4F4F83DE9D64](https://user-images.githubusercontent.com/69495129/196802351-47c16786-b53e-4107-a080-3c26089235f5.png)

라스트 커밋기준 analyze 에서 간단한 에러가 있어서 CI실패하였는데 해결 후 커밋 부탁드리고 싶습니다!

2022-10-20 00:46 UTC, CheolheeLee0 commented
> @CheolheeLee0 좋은 기여 감사합니다! ![2336B3D1-60BA-4635-B218-4F4F83DE9D64](https://user-images.githubusercontent.com/69495129/196802351-47c16786-b53e-4107-a080-3c26089235f5.png)
> 
> 라스트 커밋기준 analyze 에서 간단한 에러가 있어서 CI실패하였는데 해결 후 커밋 부탁드리고 싶습니다!

네 수정했습니다!

vscode에서 flutter_lints: ^2.0.0 에서 아래 사진처럼 problem 떠서 수정했는데, analyze에서 오류로 잡는군요!
오류메시지 읽어보니 v3.1.0 이후로 primary가 deprecated 돼서 안맞는 것 같네요!

```
'primary' is deprecated and shouldn't be used. Use backgroundColor instead. This feature was deprecated after v3.1.0..
Try replacing the use of the deprecated member with the replacement.
```

![image](https://user-images.githubusercontent.com/78692286/196830121-e7ccdf22-a16e-4a4f-b66d-e489e991f287.png)

2022-10-20 03:03 UTC, ChanhyukPark-Tech commented
> vscode

오..그렇군요 ㅠㅠ background 를쓰는게 맞는것 같은데 CI의 lint 버젼을 추후에 컨트롤하겠습니다!

2022-10-20 03:53 UTC, ChanhyukPark-Tech reviewed
우선 1차 리뷰 남겼습니다!
많은 작업 진행해주셔서 감사합니다~!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/header/go_to_home_button.dart
> +          image: const AssetImage('assets/images/common/memoji_home.png'),
![image](https://user-images.githubusercontent.com/69495129/196849944-b186e006-6fa0-498f-8055-682b7e666603.png)

이미지 네이밍 컨벤션을 정했습니다.
대문자는 사용하지 않고, snake case 로 진행합니다. 
또한 상징하는것을 앞에 적고, 뒤에는 형태를 적도록합니다. (공식문서에서 차용하였습니다 위 사진 참고.)

현재 
ex ) icon_viewcount.png => viewcount_icon.png , logo_CNB => cnb_logo 
로 바꿔주시면 될 것 같습니다.
새로 등록해주신 memoji_home.png 같은 경우는 제가 과거에 등록한 memoji02.png 와 동일한 파일로 확인했습니다.

둘중 한개만 채택하여 사용해주시면 좋을 것 같습니다!
컨벤션에 대하여 좋은 의견 있으시다면 언제든지 말씀해주세요!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/header/go_to_home_button.dart
> +          image: const AssetImage('assets/images/common/memoji_home.png'),
현재 memoji_home 을 사용하신것이 home에서 사용된다는 것을 염두하신 것 같습니다.
페이지별로 images 안에 폴더를 만들면 더 가독성이 좋을 것 같습니다.
앞으로의 진행방향은
images
  ㄴ common
  ㄴ shuttle
  ㄴ library
  ㄴ cafeteria

이러한 방식으로 진행할 것 같습니다.

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +        height: 70.h,
<img width="454" alt="image" src="https://user-images.githubusercontent.com/69495129/196850710-18bd3ad6-d348-4ba6-950d-e8ab0fa8551d.png">

현재 아이폰 14 Pro max 기준 하단에 overflow발생하는것 확인하였습니다!
이 height의 문제는 아닌것 같습니다!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/1_data/0_model/notice_model.dart
> +    required DateTime regDate,
이 데이터 스펙은 
백엔드에 따라서 바뀔 수 있는것이죠?!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/1_data/0_model/notice_model.dart
> +    required DateTime regDate,
일단 지금 백엔드 없는 상태에서 너무 잘 구성해주신 것 같아서 좋습니다!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/1_data/1_provider/notice_provider.dart
> +      '/board',
우리 백엔드 포트가 2개가 될 것 같은데
스프링 / fastapi 때문에요
그때
dioHelper의 이 부분을 컨트롤해줘야할 것 같아요!
```
options.baseUrl = EnvironmentConstant.config ?? 'test';
```

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/1_data/1_provider/notice_provider.dart
> +    dioHelper.errorCheck(result, '소식을 찾을 수 없습니다');
에러 체크를 구현한 것 좋은 것 같습니다
```
if (result['code'] != 0) {
      throw err;
  }
```
으루 구현되어있는데, 코드가 0 이아니라면 모두 에러를 throw 하는 상황인가요?

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/2_dio/dio_helper.dart
> +  policy: CachePolicy.request,
이 값은 default로 알고 있는데 값을 명시적으로 넣어줘야하는건가요?!
![image](https://user-images.githubusercontent.com/69495129/196851930-b12a376f-d0da-4236-849d-9797ac8cf47f.png)

밑에 다른 옵션들도 default인데 명시적으로 넣어주신 부분이 많은데 어떤 의도로 짜여진 건지 궁금합니다!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/3_util/date_util.dart
> +}
good😎

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/3_util/util.dart
> +}
이 유틸함수 너무 좋게 분리하신것 같은데,
파일 이름만 명시적으로 수정해주실 수 있나요?
지금은 util.dart 로만 되어있어서요!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/4_view/0_constant/constant_color.dart
> +const Color kBlue213B85 = Color(0xFF213B85);
변수명이 너무 길어지면 변수를 사용하는 의미가 크게 없을 것 같아서요!
Color 의 앞의 0xFF제외하고 그다음에 나오는 숫자나 알파벳 2자리로 짓는 컨벤션은 어떠신가요?
```suggestion
const Color kBlue00 = Color(0xFF00299F);
const Color kBlue23 = Color(0xFF233D87);
const Color kBlue21 = Color(0xFF213B85);
```

이렇게요!

2022-10-20 03:53 UTC, ChanhyukPark-Tech commented on lib/app/4_view/0_constant/constant_text_style.dart
> +);
이렇게 하나의 속성이 바뀔때마다 계속 상수를 추가해주기보다는,, 
kHeadline4처럼 크게 틀을 잡아두고 

이렇게 gray6B로 바꿔야하는경우에는
사용하는쪽에서 copyWith를 사용하는것은어떤지 의견 궁금합니다!

항상 이렇게 상수만 계속해서 생성하면 상수화하는 의미가 퇴색 될 것 같아서요! 아래에 kHeadlint50p도 같은 의견입니다!

2022-10-20 04:15 UTC, CheolheeLee0 commented on lib/app/2_dio/dio_helper.dart
> +  policy: CachePolicy.request,
```
CacheOptions dioCacheOptions = CacheOptions(
  store: MemCacheStore(), // 어디에 캐싱할 지 결정 (hive 
  policy: CachePolicy.request,
  hitCacheOnErrorExcept: [401, 403], // do not hit when this errors occur
  maxStale: const Duration(hours: 6), // 새 데이터 갱신 기준 설정
  priority: CachePriority.normal,
  cipher: null,
  keyBuilder: CacheOptions.defaultCacheKeyBuilder,
  allowPostMethod: false,
);
```

## Stores
- BackupCacheStore: Combined store with primary and secondary.
- DbCacheStore: Cache with database (Drift) [Get it](https://pub.dev/packages/dio_cache_interceptor_db_store).
- FileCacheStore: Cache with file system (Does nothing on web platform) [Get it](https://pub.dev/packages/dio_cache_interceptor_file_store).
- HiveCacheStore: Cache using Hive package (available on all platforms) [Get it](https://pub.dev/packages/dio_cache_interceptor_hive_store).
- ObjectBoxCacheStore: Cache using ObjectBox package (no web support) [Get it](https://pub.dev/packages/dio_cache_interceptor_objectbox_store).
- MemCacheStore: Volatile cache with LRU strategy.

기본 옵션이랑 동일한 부분도 있는데, store, hitcache, maxstale 같은 정보는 직접 넣어주어야 합니다!

2022-10-20 04:19 UTC, CheolheeLee0 commented on lib/app/3_util/util.dart
> +}
```
url_util.dart // url 처리 관련 함수 모음
navigate_util.dart // 화면 이동 관련 함수 모음
```
로 수정하겠습니다!

2022-10-20 04:20 UTC, CheolheeLee0 commented on lib/app/4_view/0_constant/constant_color.dart
> +const Color kBlue213B85 = Color(0xFF213B85);
네 좋은 생각인 것 같습니다!

2022-10-20 04:21 UTC, CheolheeLee0 commented on lib/app/4_view/0_constant/constant_text_style.dart
> +);
네 좋은 생각 같습니다! 수정해서 반영하겠습니다~

2022-10-20 04:21 UTC, CheolheeLee0 commented on lib/app/1_data/1_provider/notice_provider.dart
> +      '/board',
네 백엔드 서버 배포되면 구분해놓겠습니다~

2022-10-20 04:22 UTC, CheolheeLee0 commented on lib/app/1_data/1_provider/notice_provider.dart
> +    dioHelper.errorCheck(result, '소식을 찾을 수 없습니다');
아직 에러코드, 정상응답코드 합의가 안돼서, 정상 응답 코드 합의 후에 정해서 추후에 맞추는 것으로 하겠습니다!

2022-10-20 04:23 UTC, CheolheeLee0 commented on lib/app/1_data/0_model/notice_model.dart
> +    required DateTime regDate,
네 더미데이터 넣으려고 임의로 넣은 필드들입니다!

2022-10-20 04:28 UTC, CheolheeLee0 commented on lib/app/4_view/1_component/1_layout/header/go_to_home_button.dart
> +          image: const AssetImage('assets/images/common/memoji_home.png'),
네 알겠습니다! 수정해서 반영했습니다~

2022-10-20 04:43 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +        height: 70.h,
아이폰 시뮬레이터에서 sizedbox 제거하니까 overflow문제 해결되었습니다!

2022-10-20 09:37 UTC, ChanhyukPark-Tech commented on lib/app/1_data/1_provider/notice_provider.dart
> +    dioHelper.errorCheck(result, '소식을 찾을 수 없습니다');
넵~

2022-10-20 09:38 UTC, ChanhyukPark-Tech commented on lib/app/2_dio/dio_helper.dart
> +  policy: CachePolicy.request,
@CheolheeLee0 네네 저도 공식문서보고 어떠한 기능인지 확인은 했는데,
default로 정해져있는 값도 굳이 집어넣어야하나 궁금합니다!
세팅해줘야하는 값만 세팅하면 되지 않나요?!😃

2022-10-20 10:07 UTC, CheolheeLee0 commented on lib/app/2_dio/dio_helper.dart
> +  policy: CachePolicy.request,
> @CheolheeLee0 네네 저도 공식문서보고 어떠한 기능인지 확인은 했는데, default로 정해져있는 값도 굳이 집어넣어야하나 궁금합니다! 세팅해줘야하는 값만 세팅하면 되지 않나요?!😃

넵 공식문서에서 안내된대로 참고했는데, 기본값을 중복작성하는 코드로도 볼 수 있으니 지워도 좋을 것 같습니다! 반영했습니다~

2022-10-20 13:47 UTC, ChanhyukPark-Tech requested changes
몇 가지 리뷰 남겼습니다.
작성해주신 코드 보고 너무많이 배웠습니다..
머지되어도 읽어보면서 많이 배우겠습니다💪

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/board_button.dart
> +}
저는 1_component 의 역할이 페이지에서 사용되는 컴포넌트들도 보관되는 폴더라고 생각했는데
이렇게 3_notice페이지에 종속된 컴포넌트는 내부의 component폴더에 보관하는게 더 근접하고 좋네요.

과거에 1_component 안에 onboarding 폴더를 만들고 거기에 FullpageContainer 를 만들었었는데

혹시 지금 하신것과 같이
2_screen/2_onboarding 에 component 폴더를 만들고 거기로 이동시켜주실 수 있나요?
통일성을 위해서요!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/header/top_circle.dart
> +      ),
<img width="328" alt="image" src="https://user-images.githubusercontent.com/69495129/196959609-ab4fce50-61b8-4aec-8e1e-96b164abeb98.png">

용 머리는 원 안에 아직 안집어넣으신 이유가 있으신가요?!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +                              margin: EdgeInsets.fromLTRB(0.w, 142.h, 0, 0),
현재 탑에만 142.h 값을 주시려는 목적인것 같은데
그럴때 EdgeInsets.only 속성을 사용하지 않고 
항상 fromLTRB를 사용하시는 특별한 이유가 있으신가요?!🤔

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +                            const TopLogo(),
컴포넌트 분리 좋습니다!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +                              margin: EdgeInsets.fromLTRB(0.w, 142.h, 0, 0),
다른 부분도 똑같습니다!
한 부분만 값을 줘야할때 LTRB 속성을 사용하시는이유?! 가 궁금합니다~!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/board_listview.dart
> +  final Function updateBoardType;
BorderListView에서는 
updateBoardType을 필수값으로 받고있고
그것을 2개의 BorderButton의 onTap으로 넘겨주고있습니다.

BorderButton에서 onTap을 optional하게 받으시는 이유가 있으신가요?!
위에서 필수값을 받아서 그 자체를 넘기는데 값을 받지 않는 경우가 있나요?!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
이런것 궁금합니다!
왼쪽 오른쪽 끝에 같은 18.w 을 주셨는데, 이럴때 Row를 padding으로 감싸서 horizontal 18.w 을 줘도될 것 같은데 어떠한 방식을 선택할지 판단하시는 기준이 있으신가요?!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/0_constant/enum/board_type.dart
> +  }
getByDisplayName 의 역할이 궁금합니다!
따로 실행되어지고 있진 않은 것 같아서요!!!

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
이 부분 너무 정돈되게 잘 작성해주신것 같습니다.
enum타입을 map 으로 돌리면서 랜더링 할 순 없나요?

찾아보니

InternationalHqType.values.asMap().map() ... 이런식으로 하면 될 것 같은데 다트 문법이 제가 부족해서 잘 안되네요. 현재 이구조면 메뉴가 한개 추가될때마다 enum고치고 이 부분 와서 고치고 해야해서 유지보수 측면에서 안좋은것 같아서 

enum에서 정의된 것 그대로 map으로 돌면서 랜더링 하면 어떨까 고민해봤습니다..😅

2022-10-20 13:47 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +            label: '열람실',
같은 BottomNavigation 이 notice_screen에서만 사용되는것이 아닌데 이는 main.dart 와 같은 부분에서 글로벌적으로 관리할 수 없나요? 레이아웃 느낌으로요! 

현재 구조상 모든 페이지에 이 긴 BottomNavigation을 항상 붙혀줘야하는 비효율적인 구조아닌가요?!

2022-10-20 14:20 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/component/board_button.dart
> +}
네 통일성있게 해당 컴포넌트 위치 이동했습니다!

2022-10-20 14:20 UTC, CheolheeLee0 commented on lib/app/4_view/1_component/1_layout/header/top_circle.dart
> +      ),
소식 페이지는 디자인 상으로 용이 오른쪽 상단에 있는 것으로 확인되었습니다!

2022-10-20 14:21 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +                              margin: EdgeInsets.fromLTRB(0.w, 142.h, 0, 0),
저도 처음에는 only 자주 썼는데, 디자이너와 소통과정에서 픽셀 수정이 잦아, 개발 중에는 주로 fromLTRB 쓰는 것이 수정할 때 편한 것 같습니다! 이 부분은 개인차이 인것 같습니다

2022-10-20 14:21 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +                            const TopLogo(),
감사합니다!

2022-10-20 14:24 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/component/board_listview.dart
> +  final Function updateBoardType;
![image](https://user-images.githubusercontent.com/78692286/196975167-127d687a-6e46-4014-a622-fbfddaefc1c4.png)

지금까지 구현된 것으로는 onTap이 필수 값만 쓰는 경우만 있지만 위 그림처럼 버튼이 onTap 없이 텍스트 표현에 이용되는 경우도 있어서, 버튼 컴포넌트 제작할 때, onTap은 optional로 통일하는 편입니다. (Flutter 공식 위젯인 InkWell도 onTap이 optional입니다)

2022-10-20 14:42 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
Row에 패딩을 주면 아래 사진처럼 버튼이 짤리게 됩니다!

## SizedBox 사용한 경우
![image](https://user-images.githubusercontent.com/78692286/196980149-a667a04f-8a25-41be-a281-61901665b84b.png)

## Padding 사용한 경우
![image](https://user-images.githubusercontent.com/78692286/196980249-4ac14a27-4756-4a22-b760-e9676517f1ec.png)

2022-10-20 14:48 UTC, CheolheeLee0 commented on lib/app/4_view/0_constant/enum/board_type.dart
> +  }
나중에 통계 관련 기능이 생길 때, 백엔드에서 보낸 String으로 enum을 찾아야 하는 경우가 있을 것 같아서 추가해놓았습니다!

2022-10-20 15:00 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
build() 안에 map 함수를 넣으면 빌드할 때마다 함수가 실행되어 함수로 생성된 위젯들이 재빌드되는 것으로 압니다.
그래서 함수로부터 반환된 위젯들을 build 메서드 안에 넣는 것은 안좋은 패턴이라고 압니다.

```
1. function은 widget tree가 인식하지 못한다.

...반면 function을 이용 할 경우, function에서 특정 widget이 변할 경우, function 자체가 다시 호출되는 것이다. 
즉 두가지 방식에는 rebuild되는 범위의 차이가 있다. 
위의 코드처럼 간단한 예시는 상관없겠지만 코드가 복잡해지고 구조가 커진다면 이는 큰 차이로 이어지게 된다!
```

관련해 자세히 설명된 글입니다!
https://velog.io/@leeeeeoy/Flutter-Widget-Helper-Method

2022-10-20 16:24 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +            label: '열람실',
일단 BottomNavigation 컴포넌트화 했습니다!

관리할 수 있습니다! 다만 그렇게하면
홈은 이렇게 구성하고

```dart
class HomeScreen extends GetView<HomeController> {
  const HomeScreen({Key? key}) : super(key: key); 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Obx(() {
        switch (NavPage.values[controller.currentIndex.value]) {
          case NavPage.notice:
            return const NoticeScreen();
          case NavPage.food:
            return const FoodScreen();
          case NavPage.bus:
            return const BusScreen();
          case NavPage.library:
            return const LibraryScreen();
          default:
            return const ErrorScreen();
        }
      }),
      bottomNavigationBar: BottomNavBar(
        currentIndex: controller.currentIndex.value,
      ),
    );
  }
}

```

아래 처럼 app_pages의 GetPage는 못쓰게 되고, 의존성 주입을 다음과 같이 해야 합니다

```dart
class NoticeScreen extends StatelessWidget {
  const NoticeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
	// 여기에 의존성 추가해야 함.
    final controller = Get.put<NoticeController>((NoticeController(
      repository: NoticeRepository(
        provider: NoticeProvider(
          dioHelper: DioHelper(),
        ),
      ),
    )));
    return RefreshIndicator(
      onRefresh: () async {
        controller.getNoticeModelList(refresh: true);
        return Future.value();
      },
      child: Column(
        children: [

```

2022-10-20 22:00 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +                              margin: EdgeInsets.fromLTRB(0.w, 142.h, 0, 0),
와..이해했습니다 
이게 유지보수성에서 오히려좋네요!

2022-10-21 00:12 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/board_listview.dart
> +  final Function updateBoardType;
오 그렇군요!! 감사합니다~!

2022-10-21 00:12 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
헐 맞네요..!! 감사합니다

2022-10-21 00:12 UTC, ChanhyukPark-Tech commented on lib/app/4_view/0_constant/enum/board_type.dart
> +  }
좋습니다~!

2022-10-21 00:12 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
와.......

2022-10-21 00:12 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/component/international_hq_list_view.dart
> +                ),
정말감사합니다~!

2022-10-21 00:14 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/3_notice/notice_screen.dart
> +            label: '열람실',
감사합니다~!

2022-10-21 02:22 UTC, merged