feat: 학식 - 식당 선택버튼, 운영시간 UI 개발
cnu-bot/cnubot-client-app pull request #22
Opened 2022-11-28 17:40 UTC by CheolheeLee0

# Describe your changes

- 학식 페이지, 식당 선택버튼, 운영시간 UI 개발
- 폴더 이름 변경
	- 3_search 로 변경
	- 4_search_detail
	- 5_notice 로 변경
	- 6_food 로 변경
- 운영시간 json으로 저장 (operation_time_info,dart)

### 영상으로 확인하기

동작화면 영상으로 올려놓았습니다!

[![Video Label](http://img.youtube.com/vi/cCw3EBx4zNU/0.jpg)](https://www.youtube.com/shorts/cCw3EBx4zNU)
<br>

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Next Step Todo (optional)

- 학식 백엔드 API연동
- Spring 백엔드에서 보내주는 데이터에 맞춰서 freezed 모델 변경 및 식단 표시 UI 추가 개발
- 원산지(국내산 등) 파싱

## Questions

- 💬 질문 사항이에요!

2022-11-29 01:36 UTC, ChanhyukPark-Tech commented
> 제가 폴더 이름을 변경해서 pull request에서 conflict가 나는 것 같습니다! 이럴 때 git push --force 로 해결해도 될까요? 어떤 방법이 좋을지 궁금합니다!

현재 에디터에서 develop브랜치를 받으시면 에디터상에서 충돌이날것이고 거기서 해결하시고 다시 push하시면 될 것 같습니다.
일단 철희님 레포지토리에서 이 레포지토리를 업데이트 받으셔야합니다.


![image](https://user-images.githubusercontent.com/69495129/204416899-8ebe0683-0116-4035-bca5-cc22ed194208.png)


```
git remote update
```

```
git merge origin/develop
```

==> 충돌 해결

```
git add .
```

```
git commit -m "fix: resolve merge conflict"
```

```
git push origin feed-food-ui
```

2022-11-29 07:08 UTC, CheolheeLee0 commented
> 현재 에디터에서 develop브랜치를 받으시면 에디터상에서 충돌이날것이고 거기서 해결하시고 다시 push하시면 될 것 같습니다.
일단 철희님 레포지토리에서 이 레포지토리를 업데이트 받으셔야합니다.

아하 자세한 설명 감사합니다! 말씀해주신대로 merge 하니까 conflict 오류 없어졌네요!

2022-12-03 13:55 UTC, ChanhyukPark-Tech requested changes
많이 배웠습니다!

기여 감사합니다💪

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on analysis_options.yaml
> +  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
good😎

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/0_button/gray_weekday_button.dart
> +}
gray_time_button괴
gray_weekday_button 만들어주신것 정말 좋은 것같습니다!

하지만, 같은 디자인인데 추후에 time과 weekday에 관련이 없는 부분이 해당 위젯을 사용해야할 때 헷갈릴 것 같습니다!

디자인은 gray_weekday_button이라서 GrayWeekdayButton 를쓰려하는데 Weekday랑은 전혀 상관없는 도메인일수도 있습니다.

`1_component/0_button` 은 특정 도메인에 속하지 않은 common 위젯을 모아두는 곳이므로 도메인(time, weekday)을 빼고 보다 더 제네럴 하게 이름을 짓는 것은 어떨까요?

`DeepGraybutton`, `lightGrayButton`  요런 느낌으로요!

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +    final double bnbHeight = Platform.isIOS ? 110.h : 87.h;
IOS랑 다르게 처리하신 이유가 궁금합니다!

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +  final bool visible;
항상 스크롤에 따른 무언가 보여줌을 어떻게 처리해야할지 궁금했는데,
너무 잘 구현해주셔서 감사합니다. 
visible 이 바뀌는 과정에서 overflow warning 네모박스가 다음 동영상과 같이 나오는데 해결가능할까요?


https://user-images.githubusercontent.com/69495129/205443296-96f0cb78-a876-45ff-9a4e-4917a48186cb.mov

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +  final bool visible;
iphone pro max ios 16.0 환경입니다!

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +            label: NavPage.library.displayName,
index에 따른 true false 분기가 너무 반복되는데

![image](https://user-images.githubusercontent.com/69495129/205443475-5e3f94fc-af3b-468d-afec-10317255e08c.png)


다음과 같이 함수를 만들어서 해결하는것은 어떨까요?!

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/6_food/component/dat_button.dart
> +}
이 파일 명이 
`dat_button.dart`인데 `day_button.dart`로 안하신 이유가 있으신가요?!

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/6_food/component/first_sh_food_card.dart
> +                    firstShFoodModel.foodName,
![image](https://user-images.githubusercontent.com/69495129/205443674-b46d8bae-43a3-4b3c-8439-9b0b4d99e7e5.png)

이 텍스트명 현재는
```
매운차돌온
      면
```
이런식으로되어있는데

```
매운차돌온
면 
```
으로 수정하는것은어떨까요?
`textAlign.center` 를 주는것이 더이쁜가용?!

2022-12-03 13:55 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/6_food/food_controller.dart
> +  void getFirstSHFoodModelList({bool? refresh}) async {
철희님 지금까지 작업해주신 컨벤션 보면
`getFirstSHFoodModelList` => `getFirstShFoodModelList`

이렇게 되어야하는데 getFirstSHFoodModelList 로 작업하신 이유가 있으신가요?!

2022-12-03 14:17 UTC, CheolheeLee0 commented on lib/app/4_view/1_component/0_button/gray_weekday_button.dart
> +}
네 재사용하려면 그렇게 변경하는 것이 좋을 것 같습니다! 수정했습니다~

2022-12-03 14:19 UTC, CheolheeLee0 commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +    final double bnbHeight = Platform.isIOS ? 110.h : 87.h;
BottomNavigation 높이를 줄어들게 애니메이션 사용하려면 높이 설정을 해야하는데,
ios는 android와 다르게 아래 사진처럼 SafeArea 영역이 존재해서, android처럼 87.h를 하면 오버플로우가 나서 오버플로우가 안나도록 적정 높이로 설정하였습니다.

![image](https://user-images.githubusercontent.com/78692286/205445430-512aea86-d76e-4086-99e8-91517e52a8f6.png)

2022-12-03 14:28 UTC, CheolheeLee0 commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +            label: NavPage.library.displayName,
네 코드 줄이는 좋은 방법인 것 같습니다! 추가했습니다~

2022-12-03 14:29 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/6_food/component/dat_button.dart
> +}
앗 파일명 오타가 났네요 수정했습니다~

2022-12-03 14:46 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/6_food/component/first_sh_food_card.dart
> +                    firstShFoodModel.foodName,
디자인이 중앙정렬이 되어있어서 이렇게 했는데, 
왼쪽 정렬이 나은가요? 저는 둘다 괜찮은 것 같습니다!

![image](https://user-images.githubusercontent.com/78692286/205445981-40af1c59-4f60-4627-baa8-d6c95a85f0ed.png)

2022-12-03 14:47 UTC, CheolheeLee0 commented on lib/app/4_view/2_screen/6_food/food_controller.dart
> +  void getFirstSHFoodModelList({bool? refresh}) async {
맞습니다 수정했습니다!
```
SH -> Sh
```

2022-12-03 14:51 UTC, ChanhyukPark-Tech commented on lib/app/4_view/2_screen/6_food/component/first_sh_food_card.dart
> +                    firstShFoodModel.foodName,
디자인이 그렇군요! ㅠ
그러면 그렇게 중앙정렬 유지하는게 좋을 것 같습니다!😂

2022-12-03 14:57 UTC, CheolheeLee0 commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +  final bool visible;
`flutter run --release` 해서 릴리즈 환경에서는 오버플로우 박스 안보이긴 하는데, 
label을 넣으면 항상 텍스트가 있는데, height가 0이 되면서 오버플로우는 어쩔 수 없는 것 같습니다!

2022-12-03 15:11 UTC, okinawaa commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +  final bool visible;
아 release 환경에서는안보이군요! 그러면 ok입니다!

2022-12-03 15:11 UTC, ChanhyukPark-Tech commented on lib/app/4_view/1_component/1_layout/nav/bottom_nav_bar.dart
> +    final double bnbHeight = Platform.isIOS ? 110.h : 87.h;
좋습니다! 적절하게 처리하신것같아요!

2022-12-04 07:25 UTC, merged